---

GENERAL:
  interaction_mode: text
  agents: 1
  generic: True

  experience_logs:
    save: False
    load: False
    path: logs/MetalWOz_text

  global_arguments:
    domain: SlotFilling

DIALOGUE:
  num_dialogues: 10
  domain: SlotFilling


AGENT_0:
  role: system
  modules: 1

  MODULE_0:
    package: plato.agent.component.joint_model.metal_woz_seq2seq
    class: MetalWOZSeq2Seq
    arguments:
      model_path: models/joint_models/experiment_run/model
